& "$PSScriptRoot\run_decentralized_experiment.ps1" `
    -ExperimentName "cifar100/decentralized/exp_cifar100_full_graph" `
    -DatasetRoot "cifar100" `
    -PartitionMode "shards_quantity_skew" `
    -DirichletAlpha 0.5 `
    -TopologyMode "full_graph" `
    -TopologyExtraOffset 2 `
    -UsePretrained $false `
    -LocalEpochs 2 `
    -BatchSize 32 `
    -LearningRate 0.0005 `
    -WeightDecay 0.0001 `
    -NumServerRounds 30
